# Default values for argocd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

project: inventory

applicationTargets:
 - targetRevision: test
   targetNamespace: inventory-test
   applicationNames: 
   - inventory-ui
   - inventory-bff
   - inventory-svc
 - targetRevision: staging
   targetNamespace: inventory-staging
   applicationNames: 
   - inventory-ui
   - inventory-bff
   - inventory-svc
