dependencies:
  - name: nodejs-ms-demo
    version: 0.0.1
    repository: >-
      https://artifactory-tools.cntk-showcase-ocp44-vpc-0143c5dd31acd8e030a1d6e0ab1380e3-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/cntk-showcase
