global: {}

argocd-config:
  repoUrl: https://github.com/gct-showcase/inventory-gitops.git

  controllerRbac: false

  project: inventory

  applicationTargets:
    - targetRevision: test
      targetNamespace: inventory-test
      applications:
        - name: inventory-ui
        - name: inventory-bff
        - name: inventory-svc
        - name: graphql-demo
        - name: microservice-demo1

