dependencies:
  - name: inventory-svc
    version: 0.0.8
    repository: >-
      https://artifactory-tools.gct-showcase-ocp3-711085-0143c5dd31acd8e030a1d6e0ab1380e3-0001.us-east.containers.appdomain.cloud/artifactory/generic-local/gct-showcase
