dependencies:
  - name: inventory-svc
    version: 0.0.18
    repository: >-
      https://artifactory-tools.garage-dev-ocp4-c-595893-0143c5dd31acd8e030a1d6e0ab1380e3-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/dev-inventory
