dependencies:
  - name: inventory-svc
    version: 0.0.12
    repository: >-
      https://artifactory-tools.gct-showcase-ocp4-cluster-0143c5dd31acd8e030a1d6e0ab1380e3-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/gct-showcase
