# This is a basic workflow to help you get started with Actions

name: Create ServiceNow ticket

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the test branch
on:
  pull_request:
    branches: [ staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Create ticket
        run: |
          URL="${{ secrets.SERVICENOW_HOST }}/sn_chg_rest/change/standard/1"
          PAYLOAD='{"pullRequestUrl": "${{ github.event.pull_request.url }}"}'
          
          curl -X POST $URL -H "accept: application/json" -H "Content-Type: application/json" -d $PAYLOAD
